version: '3.8'

services:
  pg-saas:
    image: bitnami/postgresql:latest
    ports:
      - 5430:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=next-saas